exclude = [
    ".pytest_cache",
    "migrations",
    "tests"
]

line-length = 120
target-version = "py310"
show-fixes = true
unsafe-fixes = true

[lint]
select = [
    "A",
    "E",
    "F",
    "ISC",
    "I",
    "N",
    "PIE",
    "T20",
    "RET",
    "SLF",
    "SIM",
    "ARG",
    "ERA",
    "PL",
]

[format]
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = 80

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.isort]
case-sensitive = true
force-sort-within-sections = true
lines-after-imports = 2
lines-between-types = 1
relative-imports-order = "closest-to-furthest"
section-order = ["standard-library", "third-party", "app"]

[lint.isort.sections]
"third-party" = ["fastapi", "sqlalchemy", "pydantic"]
"app" = ["auth", "core", "interfaces", "settings", "chats"]