exclude = [
    ".pytest_cache",
    "migrations",
    "tests"
]

line-length = 100
target-version = "py310"
show-fixes = true
unsafe-fixes = true

[lint]
select = [
    "A",
    "E",
    "F",
    "ISC",
    "I",
    "N",
    "PIE",
    "T20",
    "RET",
    "SLF",
    "SIM",
    "ARG",
    "ERA",
    "PL",
]
ignore = ["SIM117"]

[format]
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = 72

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
case-sensitive = true
force-sort-within-sections = true
lines-after-imports = 2
relative-imports-order = "closest-to-furthest"
section-order = ["standard-library", "third-party", "app"]

[lint.isort.sections]
"app" = ["auth", "core", "settings", "chats", "infrastructure", "dto", "backgroud_tasks"]

[lint.pylint]
max-args = 12