"""empty message

Revision ID: add0722b47e5
Revises: e55795d17048
Create Date: 2024-05-09 21:09:36.000297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add0722b47e5"
down_revision: Union[str, None] = "e55795d17048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "email")
    # ### end Alembic commands ###
