version: 1
disable_existing_loggers: false
formatters:
  stream:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "[%(asctime)s] - %(levelname)s - %(message)s"
    use_colors: true
    datefmt: "%Y-%m-%d %H:%M:%S"
  file:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "[%(asctime)s] - %(levelname)s - %(message)s - %(filename)s - %(lineno)d"
    use_colors: false
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  file_handler:
    formatter: file
    class: logging.handlers.RotatingFileHandler
    filename: "./app.log"
    mode: a+
    maxBytes: 1000000000
    backupCount: 0
  default:
    formatter: stream
    class: logging.StreamHandler
    stream: ext://sys.stderr
loggers:
  uvicorn:
    handlers:
    - default
    - file_handler
    level: INFO
    propagate: false
  uvicorn.error:
    handlers:
    - default
    - file_handler
    level: INFO
    propagate: false
  uvicorn.access:
    handlers:
    - default
    - file_handler
    level: INFO
    propagate: false